<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Elegant Long Sleeve V-Neck Wrap Dress With Front Slit',
                'description' => 'A stunning wrap dress featuring a V-neckline and front slit. Perfect for any occasion, this elegant piece combines style with comfort.',
                'details' => 'Made from premium quality fabric. Available in multiple sizes. Machine washable.',
                'price' => 20.99,
                'original_price' => 29.99,
                'discount_percentage' => 30,
                'image' => 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
                'category' => 'Dresses',
                'rating' => 4.5,
                'rating_count' => 128,
                'featured' => true,
                'is_active' => true,
                'stock' => 50,
            ],
            [
                'name' => 'Boxy Tropical Floral Top',
                'description' => 'A vibrant tropical floral print top with a relaxed boxy fit. Perfect for summer days and casual outings.',
                'details' => '100% Cotton. Loose fit design. Easy to style with jeans or skirts.',
                'price' => 23.89,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
                'category' => 'Tops',
                'rating' => 4.2,
                'rating_count' => 95,
                'featured' => true,
                'is_active' => true,
                'stock' => 75,
            ],
            [
                'name' => 'New Classyrest Purple Floral Peplum Top',
                'description' => 'A chic peplum top with beautiful purple floral patterns. The peplum design adds a flattering silhouette to any outfit.',
                'details' => 'Polyester blend. Peplum hem design. Available in various colors.',
                'price' => 25.00,
                'original_price' => 26.00,
                'discount_percentage' => 4,
                'image' => 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
                'category' => 'Tops',
                'rating' => 4.8,
                'rating_count' => 203,
                'featured' => true,
                'is_active' => true,
                'stock' => 60,
            ],
            [
                'name' => 'High Waist Straight Summer Jeen Shorts Women',
                'description' => 'Comfortable high-waist denim shorts perfect for summer. The straight cut provides a modern, flattering fit.',
                'details' => '100% Cotton Denim. High waist design. Multiple sizes available.',
                'price' => 22.00,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
                'category' => 'Bottoms',
                'rating' => 4.3,
                'rating_count' => 156,
                'featured' => true,
                'is_active' => true,
                'stock' => 80,
            ],
            [
                'name' => 'Buy Latest Women\'s Buttoned Shirt with Spread Collar',
                'description' => 'A classic buttoned shirt with a modern spread collar. Versatile piece that can be dressed up or down.',
                'details' => 'Cotton blend. Spread collar design. Professional and casual wear.',
                'price' => 23.00,
                'original_price' => 24.00,
                'discount_percentage' => 4,
                'image' => 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
                'category' => 'Tops',
                'rating' => 4.6,
                'rating_count' => 187,
                'featured' => false,
                'is_active' => true,
                'stock' => 45,
            ],
            [
                'name' => 'Mas Ultralightweight, Premiun Summer Slipper',
                'description' => 'Lightweight and comfortable summer slippers perfect for casual wear. Premium quality materials for ultimate comfort.',
                'details' => 'Ultra-lightweight design. Premium materials. Perfect for summer.',
                'price' => 15.00,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=1000&fit=crop',
                'category' => 'Footwear',
                'rating' => 3.5,
                'rating_count' => 42,
                'featured' => false,
                'is_active' => true,
                'stock' => 100,
            ],
            [
                'name' => 'White Button-Down Floral Dress',
                'description' => 'A beautiful white dress with yellow floral patterns. The button-down design adds a classic touch to this elegant piece.',
                'details' => 'Cotton blend. Button-down front. Cinched waist design.',
                'price' => 28.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
                'category' => 'Dresses',
                'rating' => 4.7,
                'rating_count' => 234,
                'featured' => false,
                'is_active' => true,
                'stock' => 35,
            ],
            [
                'name' => 'Light Blue Long Sleeved Top',
                'description' => 'A comfortable long-sleeved top in a soothing light blue color. Perfect for layering or wearing alone.',
                'details' => 'Soft cotton material. Long sleeves. Versatile styling options.',
                'price' => 19.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=1000&fit=crop',
                'category' => 'Tops',
                'rating' => 4.4,
                'rating_count' => 112,
                'featured' => false,
                'is_active' => true,
                'stock' => 90,
            ],
            [
                'name' => 'Yellow Ruffled Top',
                'description' => 'A vibrant yellow top with elegant ruffled details. The ruffles add texture and movement to this stylish piece.',
                'details' => 'Ruffled design. Bright yellow color. Perfect for spring and summer.',
                'price' => 24.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=1000&fit=crop',
                'category' => 'Tops',
                'rating' => 4.1,
                'rating_count' => 78,
                'featured' => false,
                'is_active' => true,
                'stock' => 55,
            ],
            [
                'name' => 'Maroon Sleeveless Vest with Matching Pants',
                'description' => 'A sophisticated maroon vest and pants set. The sleeveless vest pairs perfectly with the matching high-waist pants.',
                'details' => 'Matching set. Sleeveless vest design. High-waist pants.',
                'price' => 35.99,
                'original_price' => 42.99,
                'discount_percentage' => 16,
                'image' => 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
                'category' => 'Sets',
                'rating' => 4.5,
                'rating_count' => 145,
                'featured' => false,
                'is_active' => true,
                'stock' => 30,
            ],
            [
                'name' => 'Light Pink Cropped Blazer with Pants',
                'description' => 'A chic light pink cropped blazer worn over a black top, paired with matching light pink high-waist pants.',
                'details' => 'Cropped blazer design. Matching pants set. Professional yet stylish.',
                'price' => 45.99,
                'original_price' => 52.99,
                'discount_percentage' => 13,
                'image' => 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=1000&fit=crop',
                'category' => 'Sets',
                'rating' => 4.6,
                'rating_count' => 198,
                'featured' => false,
                'is_active' => true,
                'stock' => 25,
            ],
            [
                'name' => 'White Sleeveless V-Neck Top with Pleated Skirt',
                'description' => 'A classic white sleeveless V-neck top paired with a white pleated skirt with subtle polka dots.',
                'details' => 'Two-piece set. V-neck design. Pleated skirt with polka dots.',
                'price' => 32.99,
                'original_price' => null,
                'discount_percentage' => 0,
                'image' => 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
                'category' => 'Sets',
                'rating' => 4.8,
                'rating_count' => 267,
                'featured' => false,
                'is_active' => true,
                'stock' => 40,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Successfully seeded ' . count($products) . ' products!');
    }
}
